### ISSUE TITLE
Passing spark-defaults.conf values as part of spring cloud task modules

### ISSUE THREAD

**Issue by rejurs** [spring-cloud/spring-cloud-task-modules#36]
Hi Team,

Could you please help me to pass the spark-defaults.conf values when we are running **java -jar sparkapp-yarn/target/sparkapp-yarn-task-1.0.0.BUILD-SNAPSHOT-exec.jar**.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-task-app-starters#18
