### ISSUE TITLE
Port gpload as s-c-t module

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task-modules#7]
As a developer, I'd like to move *gpload* module from XD to s-c-t-m repo, so I can use it as task to build batch pipelines. 

**Acceptance:**
* *gpload* as task module (Spring Boot App) is available in *spring-cloud-task-modules* repo 
* maven coordinates include *gpload* with respective group/artifact/version

**Comment by trisberg** [comment]
Wonder if we should even do this one. The XD module depends on a binary install of  Greenplum utilities on the container that runs the job. Adds a lot of complexity, probably doesn't work on CF.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-task-app-starters#12
